### ISSUE TITLE
canducci/cep older versions

### ISSUE THREAD

**Issue by gpedro** [netdragoon/canduccicep#1]
eu pude notar que recentemente ouve uma alteração **major** neste pacote, ou seja, que há alterações em sua api, se possível, sugiro que dê release em uma versão **0.0.1** para continuar dando compatibilidade para os que já utilizavam seu módulo.

Obrigado.

**Comment by netdragoon** [comment]
eu peço mil desculpas, mas, acabei tendo um motivo para isso (muito desagradável) que afetou o versionamentos. 
Eu não tenho as versões anteriores, por acaso, você usa meu pacote ?

**Comment by gpedro** [comment]
:( eu uso seu pacote. Acredito que muita gente usa, inclusive. Irei te
mandar a versão que possui amanhã.
Em 26 de out de 2015 8:00 PM, "NetDragoon" notifications@github.com
escreveu:

**Comment by gpedro** [comment]
@netdragoon http://speedy.sh/bm3XE/ee052b3e2ada67f7a85dbb88b72760b4f8e11120.zip

**Comment by gpedro** [comment]
@netdragoon ping!

**Comment by netdragoon** [comment]
@gpedro pong! 

Eu coloquei em outro branch e disponibilize é isso que você queria ???

**Comment by gpedro** [comment]
subir essa versão antiga no repo e versionar ela no composer.

**Comment by netdragoon** [comment]
Feito
