### ISSUE TITLE
Erro na busca por CEP

### ISSUE THREAD

**Issue by dlimars** [netdragoon/canduccicep#2]
Após uma busca pelo CEP: 18071-051, só me retornava "null" como resultado, após análise, constatei que o erro era causado porque o nome da rua é "Rua Constantino Verrone", que ao rodar o método `validation`, o mesmo acusava erro:

```
    private function validation($get)
    {
        return !((int)preg_match('/(erro)/', $get) === 1);
    } 
```

ou seja, todos os ceps que contiverem a palavra `erro` no endereço irão falhar

**Comment by dlimars** [comment]
Outro exemplo é com o cep `97542080` cujo nome da rua é `Rua Barão de Cerro Largo`

**Comment by fulviocanducci** [comment]
Caro @dlimars  tudo bem, espero que sim! Agradeço a abertura do ISSUE!

Mas, 

Eu acabei de testar o código inclusive tem uma página http://zipcodedemo.herokuapp.com/ que também funcionou corretamente o código. Aquele busca da palavra "erro" até vou verificar, mas, não é por causa disso que não trouxe o resultado, porque nos testes feitos funcionaram inclusive no site

Observe:

![save12389](https://user-images.githubusercontent.com/25593291/32725918-26a1e722-c85e-11e7-9d8b-970fadac493b.png)

Um outro observação é que quando dá erro seria assim:

![erro](https://user-images.githubusercontent.com/25593291/32726006-85ab4a42-c85e-11e7-9a21-240802873626.png)


Qualquer coisa me mande o seu código e como esta resgatando, por favor?

Muito Obrigado!

**Comment by dlimars** [comment]
Opa @fulviocanducci , então, antes de postar, utilizei a página demo também, mas olha como estou utilizando:
<img width="313" alt="screen shot 2017-11-13 at 10 47 14" src="https://user-images.githubusercontent.com/4266198/32726459-3d45a53e-c860-11e7-81f4-3b015e4e21af.png">

e este é o resultado:
<img width="221" alt="screen shot 2017-11-13 at 10 49 08" src="https://user-images.githubusercontent.com/4266198/32726483-528a63da-c860-11e7-8814-dbd233734462.png">

Quanto ao erro, eu resolvi colocar um dump antes do retorno do parser, da seguinte forma:
<img width="419" alt="screen shot 2017-11-13 at 10 51 58" src="https://user-images.githubusercontent.com/4266198/32726641-c99304a0-c860-11e7-9181-9ea7f054c981.png">

e olha o resultado:
<img width="369" alt="screen shot 2017-11-13 at 10 53 04" src="https://user-images.githubusercontent.com/4266198/32726658-df26c0e0-c860-11e7-971c-e207f8cb25bb.png">

Nota que o segundo parâmetro retorna `false` que é o que roda a validação.
Nota que o método `validation($get)` roda sobre o retorno inteiro da consulta e não apenas verificando o retorno `{ "erro" : "true" }` como você comentou.

**Comment by fulviocanducci** [comment]
@dlimars já estou verificando porque realmente é um bug! Peço a compreensão e logo mais já posto a solução e a nova versão do Canducci Cep. e Muito obrigado pela observação!

Quando postar já te aviso.!

**Comment by fulviocanducci** [comment]
@dlimars bug resolvido.! Nova versão

https://packagist.org/packages/canducci/cep#v2.0.2

Qualquer problemas, pode avisar e obrigado.

Uma pergunta você utiliza ele fora do Laravel?

**Comment by dlimars** [comment]
Opa, obrigado @fulviocanducci, na verdade eu uso com Laravel, eu só não sou muito chegado nos Facades, pq?

**Comment by netdragoon** [comment]
@dlimars se for utilizar para Laravel utilize esse:

https://packagist.org/packages/canducci/zipcode

Ele otimiza o desempenho e só busca se não tiver no cache. é útil porque diminui o numero de requisições.

Se esse pacote deu certo se poderia comentar eu fiz vários testes e agora acredito que não terá problemas!

**Comment by dlimars** [comment]
Opa @netdragoon @fulviocanducci deu certinho a correção, muito obrigado!
